---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`4 + 4` vale 8"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`"4" + "4"` vale `"44"`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`4 + 4` vale `"44"`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`"on" + "ce"` vale `"once"`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`true && false` vale `false`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`true && false` vale `0`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`5 >= 6` vale `false`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`! true` vale `false`"
  checked: true
name: Datos de todo tipo
